#!/usr/bin/env perl



#@instructions = ("ULL","RRDDD","LURDL","UUUUD"); #sample
# assignment (ans. 14894) 
#@instructions = 
#("URULLLLLRLDDUURRRULLLDURRDRDRDLURURURLDLLLLRUDDRRLUDDDDDDLRLRDDDUUDUDLDULUDLDURDULLRDDURLLLRRRLLRURLLUDRDLLRRLDDRUDULRRDDLUUUDRLDLURRRULURRDLLLDDDLUDURDDRLDDDLLRULDRUDDDLUDLURUDLLRURRUURUDLLLUUUUDDURDRDDDLDRRUDURDLLLULUDURURDUUULRULUDRUUUUDLRLUUUUUDDRRDDDURULLLRRLDURLDLDRDLLLUULLRRLLLLDRLRDRRDRRUDDLULUUDDDDRRUUDDLURLRDUUDRRLDUDLRRRLRRUUDURDRULULRDURDRRRDLDUUULRDDLRLRDLUUDDUDDRLRRULLLULULLDDDRRDUUUDDRURDDURDRLRDLDRDRULRLUURUDRLULRLURLRRULDRLRDUDLDURLLRLUDLUDDURDUURLUDRLUL",
#"LLLUUURUULDDDULRRDLRLLLLLLLLRURRDLURLUDRRDDULDRRRRRRLDURRULDDULLDDDRUUDLUDULLDLRRLUULULRULURDURLLDULURDUDLRRLRLLDULLRLDURRUULDLDULLRDULULLLULDRLDLDLDLDDLULRLDUDRULUDDRDDRLRLURURRDULLUULLDRRDRRDLDLLRDLDDUUURLUULDDRRRUULDULDDRDDLULUDRURUULLUDRURDRULDRUULLRRDURUDDLDUULLDDRLRRDUDRLRRRLDRLRULDRDRRUDRLLLDDUDLULLURRURRLUURDRLLDLLDUDLUUURRLRDDUDRLUDLLRULLDUUURDLUUUDUDULRLDLDRUUDULRDRRUDLULRLRDLDRRDDDUDLDLDLRUURLDLLUURDLDLRDLDRUDDUURLLLRDRDRRULLRLRDULUDDDLUDURLDUDLLRULRDURDRDLLULRRDLLLDUURRDUDDLDDRULRRRRLRDDRURLLRRLLL",
#"DRURLDDDDRLUDRDURUDDULLRRLLRLDDRLULURLDURRLDRRLRLUURDDRRDLRDLDLULDURUDRLRUDULRURURLRUDRLLDDUDDRDLDRLLDDLRRDRUUULDUUDRUULRLLDLLULLLRRDRURDLDDRRDDUDDULLDUUULDRUDLDLURLDRURUDLRDDDURRLRDDUDLLLRRUDRULRULRRLLUUULDRLRRRLLLDLLDUDDUUDRURLDLRRUUURLUDDDRRDDLDDDDLUURDDULDRLRURLULLURRDRLLURLLLURDURLDLUDUUDUULLRLDLLLLULRDDLDUDUDDDUULURRLULDLDRLRDRLULLUDDUUUUURDRURLDUULDRRDULUDUDLDDRDLUDDURUDURLDULRUDRRDLRLRDRRURLDLURLULULDDUUDLRLLLLURRURULDDRUUULLDULDRDULDDDLLLRLULDDUDLRUDUDUDURLURLDDLRULDLURD",
#"DRUDRDURUURDLRLUUUUURUDLRDUURLLDUULDUULDLURDDUULDRDDRDULUDDDRRRRLDDUURLRDLLRLRURDRRRDURDULRLDRDURUDLLDDULRDUDULRRLLUDLLUUURDULRDDLURULRURDDLRLLULUDURDRRUDLULLRLDUDLURUDRUULDUDLRDUDRRDULDDLDRLRRULURULUURDULRRLDLDULULRUUUUULUURLURLRDLLRRRRLURRUDLRLDDDLDRDRURLULRDUDLRLURRDRRLRLLDLDDLLRRULRLRLRUDRUUULLDUULLDDRLUDDRURLRLDLULDURLLRRLDLLRDDDUDDUULLUDRUDURLLRDRUDLUDLLUDRUUDLRUURRRLLUULLUUURLLLRURUULLDLLDURUUUULDDDLRLURDRLRRRRRRUDLLLRUUULDRRDLRDLLDRDLDDLDLRDUDLDDRDDDDRULRRLRDULLDULULULRULLRRLLUURUUUDLDLUDUDDDLUUDDDDUDDDUURUUDRDURRLUULRRDUUDDUDRRRDLRDRLDLRRURUUDRRRUUDLDRLRDURD",
#"DDDLRURUDRRRURUUDLRLRDULDRDUULRURRRUULUDULDDLRRLLRLDDLURLRUDRLRRLRDLRLLDDLULDLRRURDDRDLLDDRUDRRRURRDUDULUDDULRRDRLDUULDLLLDRLUDRDURDRRDLLLLRRLRLLULRURUUDDRULDLLRULDRDLUDLULDDDLLUULRRLDDUURDLULUULULRDDDLDUDDLLLRRLLLDULRDDLRRUDDRDDLLLLDLDLULRRRDUDURRLUUDLLLLDUUULDULRDRULLRDRUDULRUUDULULDRDLDUDRRLRRDRLDUDLULLUDDLURLUUUDRDUDRULULDRDLRDRRLDDRRLUURDRULDLRRLLRRLDLRRLDLDRULDDRLURDULRRUDURRUURDUUURULUUUDLRRLDRDLULDURUDUDLUDDDULULRULDRRRLRURLRLRLUDDLUUDRRRLUUUDURLDRLRRDRRDURLLL")
#;

# simplified assignment set (also 14894) 
@instructions = 
("URULLRLDDUURRULLDURRDRDRDLURURURLDLLRUDDRRLUDDLRLRDDUUDUDLDULUDLDURDULLRDDURLLRRLLRURLLUDRDLLRRLDDRUDULRRDDLUUDRLDLURRULURRDLLDDLUDURDDRLDDLLRULDRUDDLUDLURUDLLRURRUURUDLLUUDDURDRDDLDRRUDURDLLULUDURURDUULRULUDRUUDLRLUUDDRRDDURULLRRLDURLDLDRDLLUULLRRLLDRLRDRRDRRUDDLULUUDDRRUUDDLURLRDUUDRRLDUDLRRLRRUUDURDRULULRDURDRRDLDUULRDDLRLRDLUUDDUDDRLRRULLULULLDDRRDUUDDRURDDURDRLRDLDRDRULRLUURUDRLULRLURLRRULDRLRDUDLDURLLRLUDLUDDURDUURLUDRLUL",
"LLUURUULDDULRRDLRLLRURRDLURLUDRRDDULDRRLDURRULDDULLDDRUUDLUDULLDLRRLUULULRULURDURLLDULURDUDLRRLRLLDULLRLDURRUULDLDULLRDULULLULDRLDLDLDLDDLULRLDUDRULUDDRDDRLRLURURRDULLUULLDRRDRRDLDLLRDLDDUURLUULDDRRUULDULDDRDDLULUDRURUULLUDRURDRULDRUULLRRDURUDDLDUULLDDRLRRDUDRLRRLDRLRULDRDRRUDRLLDDUDLULLURRURRLUURDRLLDLLDUDLUURRLRDDUDRLUDLLRULLDUURDLUUDUDULRLDLDRUUDULRDRRUDLULRLRDLDRRDDUDLDLDLRUURLDLLUURDLDLRDLDRUDDUURLLRDRDRRULLRLRDULUDDLUDURLDUDLLRULRDURDRDLLULRRDLLDUURRDUDDLDDRULRRLRDDRURLLRRLL",
"DRURLDDRLUDRDURUDDULLRRLLRLDDRLULURLDURRLDRRLRLUURDDRRDLRDLDLULDURUDRLRUDULRURURLRUDRLLDDUDDRDLDRLLDDLRRDRUULDUUDRUULRLLDLLULLRRDRURDLDDRRDDUDDULLDUULDRUDLDLURLDRURUDLRDDURRLRDDUDLLRRUDRULRULRRLLUULDRLRRLLDLLDUDDUUDRURLDLRRUURLUDDRRDDLDDLUURDDULDRLRURLULLURRDRLLURLLURDURLDLUDUUDUULLRLDLLULRDDLDUDUDDUULURRLULDLDRLRDRLULLUDDUURDRURLDUULDRRDULUDUDLDDRDLUDDURUDURLDULRUDRRDLRLRDRRURLDLURLULULDDUUDLRLLURRURULDDRUULLDULDRDULDDLLRLULDDUDLRUDUDUDURLURLDDLRULDLURD",
"DRUDRDURUURDLRLUURUDLRDUURLLDUULDUULDLURDDUULDRDDRDULUDDRRLDDUURLRDLLRLRURDRRDURDULRLDRDURUDLLDDULRDUDULRRLLUDLLUURDULRDDLURULRURDDLRLLULUDURDRRUDLULLRLDUDLURUDRUULDUDLRDUDRRDULDDLDRLRRULURULUURDULRRLDLDULULRUULUURLURLRDLLRRLURRUDLRLDDLDRDRURLULRDUDLRLURRDRRLRLLDLDDLLRRULRLRLRUDRUULLDUULLDDRLUDDRURLRLDLULDURLLRRLDLLRDDUDDUULLUDRUDURLLRDRUDLUDLLUDRUUDLRUURRLLUULLUURLLRURUULLDLLDURUULDDLRLURDRLRRUDLLRUULDRRDLRDLLDRDLDDLDLRDUDLDDRDDRULRRLRDULLDULULULRULLRRLLUURUUDLDLUDUDDLUUDDUDDUURUUDRDURRLUULRRDUUDDUDRRDLRDRLDLRRURUUDRRUUDLDRLRDURD",
"DDLRURUDRRURUUDLRLRDULDRDUULRURRUULUDULDDLRRLLRLDDLURLRUDRLRRLRDLRLLDDLULDLRRURDDRDLLDDRUDRRURRDUDULUDDULRRDRLDUULDLLDRLUDRDURDRRDLLRRLRLLULRURUUDDRULDLLRULDRDLUDLULDDLLUULRRLDDUURDLULUULULRDDLDUDDLLRRLLDULRDDLRRUDDRDDLLDLDLULRRDUDURRLUUDLLDUULDULRDRULLRDRUDULRUUDULULDRDLDUDRRLRRDRLDUDLULLUDDLURLUUDRDUDRULULDRDLRDRRLDDRRLUURDRULDLRRLLRRLDLRRLDLDRULDDRLURDULRRUDURRUURDUURULUUDLRRLDRDLULDURUDUDLUDDULULRULDRRLRURLRLRLUDDLUUDRRLUUDURLDRLRRDRRDURLL")
;

$curr = 5; #start in center of keypad

$digits = @instructions; #get a count of the number of digits in the code

for ($x=0; $x < $digits; $x++) {

print "Working on digit $x of $digits\n";

	for ($y = 0; $y < length($instructions[$x]); $y++) {
		$m = substr ($instructions[$x], $y, 1);  
		#print "$m: ";
		if	($m eq "R"){
			
				if ($curr== 1) { $curr = 2 ;}
				elsif ($curr== 2) { $curr = 3 ;}
				elsif ($curr== 3){ $curr = 3 ;}
				elsif ($curr== 4) { $curr = 5 ;}
				elsif ($curr== 5) { $curr = 6 ;}
				elsif ($curr== 6) { $curr = 6 ;}
				elsif ($curr== 7) { $curr = 8 ;}
				elsif ($curr== 8) { $curr = 9 ;}
				elsif ($curr== 9) { $curr = 9 ;}
			
		} elsif ($m eq "L"){
				if ($curr== 1) { $curr = 1 ;}
				elsif ($curr== 2) { $curr = 1 ;}
				elsif ($curr== 3){ $curr = 2 ;}
				elsif ($curr== 4) { $curr = 4 ;}
				elsif ($curr== 5) { $curr = 4 ;}
				elsif ($curr== 6) { $curr = 5 ;}
				elsif ($curr== 7) { $curr = 7 ;}
				elsif ($curr== 8) { $curr = 7 ;}
				elsif ($curr== 9) { $curr = 8 ;}
			
		} elsif ($m eq "U"){
				if ($curr== 1) { $curr = 1 ;}
				elsif ($curr== 2) { $curr = 2 ;}
				elsif ($curr== 3){ $curr = 3 ;}
				elsif ($curr== 4) { $curr = 1 ;}
				elsif ($curr== 5) { $curr = 2 ;}
				elsif ($curr== 6) { $curr = 3 ;}
				elsif ($curr== 7) { $curr = 4 ;}
				elsif ($curr== 8) { $curr = 5 ;}
				elsif ($curr== 9) { $curr = 6 ;}
			
		} elsif ($m eq "D"){
				if ($curr== 1) { $curr = 4 ;}
				elsif ($curr== 2) { $curr = 5 ;}
				elsif ($curr== 3){ $curr = 6 ;}
				elsif ($curr== 4) { $curr = 7 ;}
				elsif ($curr== 5) { $curr = 8 ;}
				elsif ($curr== 6) { $curr = 9 ;}
				elsif ($curr== 7) { $curr = 7 ;}
				elsif ($curr== 8) { $curr = 8 ;}
				elsif ($curr== 9)  { $curr = 9 ;}
			
		}
		#print "$curr \n";
	}
	$code = $code . "$curr"; 
	print "$code \n";

}

print "done. Final code is $code. \n";

