#!/usr/bin/env perl

#keypad
#    1
#  2 3 4
#5 6 7 8 9
#  A B C
#    D



#@instructions = ("ULL","RRDDD","LURDL","UUUUD"); #sample (5DB3)

# assignment  (26B96)
@instructions = 
("URULLLLLRLDDUURRRULLLDURRDRDRDLURURURLDLLLLRUDDRRLUDDDDDDLRLRDDDUUDUDLDULUDLDURDULLRDDURLLLRRRLLRURLLUDRDLLRRLDDRUDULRRDDLUUUDRLDLURRRULURRDLLLDDDLUDURDDRLDDDLLRULDRUDDDLUDLURUDLLRURRUURUDLLLUUUUDDURDRDDDLDRRUDURDLLLULUDURURDUUULRULUDRUUUUDLRLUUUUUDDRRDDDURULLLRRLDURLDLDRDLLLUULLRRLLLLDRLRDRRDRRUDDLULUUDDDDRRUUDDLURLRDUUDRRLDUDLRRRLRRUUDURDRULULRDURDRRRDLDUUULRDDLRLRDLUUDDUDDRLRRULLLULULLDDDRRDUUUDDRURDDURDRLRDLDRDRULRLUURUDRLULRLURLRRULDRLRDUDLDURLLRLUDLUDDURDUURLUDRLUL",
"LLLUUURUULDDDULRRDLRLLLLLLLLRURRDLURLUDRRDDULDRRRRRRLDURRULDDULLDDDRUUDLUDULLDLRRLUULULRULURDURLLDULURDUDLRRLRLLDULLRLDURRUULDLDULLRDULULLLULDRLDLDLDLDDLULRLDUDRULUDDRDDRLRLURURRDULLUULLDRRDRRDLDLLRDLDDUUURLUULDDRRRUULDULDDRDDLULUDRURUULLUDRURDRULDRUULLRRDURUDDLDUULLDDRLRRDUDRLRRRLDRLRULDRDRRUDRLLLDDUDLULLURRURRLUURDRLLDLLDUDLUUURRLRDDUDRLUDLLRULLDUUURDLUUUDUDULRLDLDRUUDULRDRRUDLULRLRDLDRRDDDUDLDLDLRUURLDLLUURDLDLRDLDRUDDUURLLLRDRDRRULLRLRDULUDDDLUDURLDUDLLRULRDURDRDLLULRRDLLLDUURRDUDDLDDRULRRRRLRDDRURLLRRLLL",
"DRURLDDDDRLUDRDURUDDULLRRLLRLDDRLULURLDURRLDRRLRLUURDDRRDLRDLDLULDURUDRLRUDULRURURLRUDRLLDDUDDRDLDRLLDDLRRDRUUULDUUDRUULRLLDLLULLLRRDRURDLDDRRDDUDDULLDUUULDRUDLDLURLDRURUDLRDDDURRLRDDUDLLLRRUDRULRULRRLLUUULDRLRRRLLLDLLDUDDUUDRURLDLRRUUURLUDDDRRDDLDDDDLUURDDULDRLRURLULLURRDRLLURLLLURDURLDLUDUUDUULLRLDLLLLULRDDLDUDUDDDUULURRLULDLDRLRDRLULLUDDUUUUURDRURLDUULDRRDULUDUDLDDRDLUDDURUDURLDULRUDRRDLRLRDRRURLDLURLULULDDUUDLRLLLLURRURULDDRUUULLDULDRDULDDDLLLRLULDDUDLRUDUDUDURLURLDDLRULDLURD",
"DRUDRDURUURDLRLUUUUURUDLRDUURLLDUULDUULDLURDDUULDRDDRDULUDDDRRRRLDDUURLRDLLRLRURDRRRDURDULRLDRDURUDLLDDULRDUDULRRLLUDLLUUURDULRDDLURULRURDDLRLLULUDURDRRUDLULLRLDUDLURUDRUULDUDLRDUDRRDULDDLDRLRRULURULUURDULRRLDLDULULRUUUUULUURLURLRDLLRRRRLURRUDLRLDDDLDRDRURLULRDUDLRLURRDRRLRLLDLDDLLRRULRLRLRUDRUUULLDUULLDDRLUDDRURLRLDLULDURLLRRLDLLRDDDUDDUULLUDRUDURLLRDRUDLUDLLUDRUUDLRUURRRLLUULLUUURLLLRURUULLDLLDURUUUULDDDLRLURDRLRRRRRRUDLLLRUUULDRRDLRDLLDRDLDDLDLRDUDLDDRDDDDRULRRLRDULLDULULULRULLRRLLUURUUUDLDLUDUDDDLUUDDDDUDDDUURUUDRDURRLUULRRDUUDDUDRRRDLRDRLDLRRURUUDRRRUUDLDRLRDURD",
"DDDLRURUDRRRURUUDLRLRDULDRDUULRURRRUULUDULDDLRRLLRLDDLURLRUDRLRRLRDLRLLDDLULDLRRURDDRDLLDDRUDRRRURRDUDULUDDULRRDRLDUULDLLLDRLUDRDURDRRDLLLLRRLRLLULRURUUDDRULDLLRULDRDLUDLULDDDLLUULRRLDDUURDLULUULULRDDDLDUDDLLLRRLLLDULRDDLRRUDDRDDLLLLDLDLULRRRDUDURRLUUDLLLLDUUULDULRDRULLRDRUDULRUUDULULDRDLDUDRRLRRDRLDUDLULLUDDLURLUUUDRDUDRULULDRDLRDRRLDDRRLUURDRULDLRRLLRRLDLRRLDLDRULDDRLURDULRRUDURRUURDUUURULUUUDLRRLDRDLULDURUDUDLUDDDULULRULDRRRLRURLRLRLUDDLUUDRRRLUUUDURLDRLRRDRRDURLLL")
;

# simplified assignment set  
#@instructions = 
#("URULLRLDDUURRULLDURRDRDRDLURURURLDLLRUDDRRLUDDLRLRDDUUDUDLDULUDLDURDULLRDDURLLRRLLRURLLUDRDLLRRLDDRUDULRRDDLUUDRLDLURRULURRDLLDDLUDURDDRLDDLLRULDRUDDLUDLURUDLLRURRUURUDLLUUDDURDRDDLDRRUDURDLLULUDURURDUULRULUDRUUDLRLUUDDRRDDURULLRRLDURLDLDRDLLUULLRRLLDRLRDRRDRRUDDLULUUDDRRUUDDLURLRDUUDRRLDUDLRRLRRUUDURDRULULRDURDRRDLDUULRDDLRLRDLUUDDUDDRLRRULLULULLDDRRDUUDDRURDDURDRLRDLDRDRULRLUURUDRLULRLURLRRULDRLRDUDLDURLLRLUDLUDDURDUURLUDRLUL",
#"LLUURUULDDULRRDLRLLRURRDLURLUDRRDDULDRRLDURRULDDULLDDRUUDLUDULLDLRRLUULULRULURDURLLDULURDUDLRRLRLLDULLRLDURRUULDLDULLRDULULLULDRLDLDLDLDDLULRLDUDRULUDDRDDRLRLURURRDULLUULLDRRDRRDLDLLRDLDDUURLUULDDRRUULDULDDRDDLULUDRURUULLUDRURDRULDRUULLRRDURUDDLDUULLDDRLRRDUDRLRRLDRLRULDRDRRUDRLLDDUDLULLURRURRLUURDRLLDLLDUDLUURRLRDDUDRLUDLLRULLDUURDLUUDUDULRLDLDRUUDULRDRRUDLULRLRDLDRRDDUDLDLDLRUURLDLLUURDLDLRDLDRUDDUURLLRDRDRRULLRLRDULUDDLUDURLDUDLLRULRDURDRDLLULRRDLLDUURRDUDDLDDRULRRLRDDRURLLRRLL",
#"DRURLDDRLUDRDURUDDULLRRLLRLDDRLULURLDURRLDRRLRLUURDDRRDLRDLDLULDURUDRLRUDULRURURLRUDRLLDDUDDRDLDRLLDDLRRDRUULDUUDRUULRLLDLLULLRRDRURDLDDRRDDUDDULLDUULDRUDLDLURLDRURUDLRDDURRLRDDUDLLRRUDRULRULRRLLUULDRLRRLLDLLDUDDUUDRURLDLRRUURLUDDRRDDLDDLUURDDULDRLRURLULLURRDRLLURLLURDURLDLUDUUDUULLRLDLLULRDDLDUDUDDUULURRLULDLDRLRDRLULLUDDUURDRURLDUULDRRDULUDUDLDDRDLUDDURUDURLDULRUDRRDLRLRDRRURLDLURLULULDDUUDLRLLURRURULDDRUULLDULDRDULDDLLRLULDDUDLRUDUDUDURLURLDDLRULDLURD",
#"DRUDRDURUURDLRLUURUDLRDUURLLDUULDUULDLURDDUULDRDDRDULUDDRRLDDUURLRDLLRLRURDRRDURDULRLDRDURUDLLDDULRDUDULRRLLUDLLUURDULRDDLURULRURDDLRLLULUDURDRRUDLULLRLDUDLURUDRUULDUDLRDUDRRDULDDLDRLRRULURULUURDULRRLDLDULULRUULUURLURLRDLLRRLURRUDLRLDDLDRDRURLULRDUDLRLURRDRRLRLLDLDDLLRRULRLRLRUDRUULLDUULLDDRLUDDRURLRLDLULDURLLRRLDLLRDDUDDUULLUDRUDURLLRDRUDLUDLLUDRUUDLRUURRLLUULLUURLLRURUULLDLLDURUULDDLRLURDRLRRUDLLRUULDRRDLRDLLDRDLDDLDLRDUDLDDRDDRULRRLRDULLDULULULRULLRRLLUURUUDLDLUDUDDLUUDDUDDUURUUDRDURRLUULRRDUUDDUDRRDLRDRLDLRRURUUDRRUUDLDRLRDURD",
#"DDLRURUDRRURUUDLRLRDULDRDUULRURRUULUDULDDLRRLLRLDDLURLRUDRLRRLRDLRLLDDLULDLRRURDDRDLLDDRUDRRURRDUDULUDDULRRDRLDUULDLLDRLUDRDURDRRDLLRRLRLLULRURUUDDRULDLLRULDRDLUDLULDDLLUULRRLDDUURDLULUULULRDDLDUDDLLRRLLDULRDDLRRUDDRDDLLDLDLULRRDUDURRLUUDLLDUULDULRDRULLRDRUDULRUUDULULDRDLDUDRRLRRDRLDUDLULLUDDLURLUUDRDUDRULULDRDLRDRRLDDRRLUURDRULDLRRLLRRLDLRRLDLDRULDDRLURDULRRUDURRUURDUURULUUDLRRLDRDLULDURUDUDLUDDULULRULDRRLRURLRLRLUDDLUUDRRLUUDURLDRLRRDRRDURLL")
#;

$curr = 5; #start in center of keypad

$digits = @instructions; #get a count of the number of digits in the code

for ($x=0; $x < $digits; $x++) {

print "Working on digit $x of $digits\n";

	for ($y = 0; $y < length($instructions[$x]); $y++) {
		$m = substr ($instructions[$x], $y, 1);  
		#print "$m: ";
		if	($m eq "R"){
			
				if ($curr eq "1") { $curr = "1" ;}
				elsif ($curr eq "2") { $curr = "3" ;}
				elsif ($curr eq "3") { $curr = "4" ;}
				elsif ($curr eq "4") { $curr = "4" ;}
				elsif ($curr eq "5") { $curr = "6" ;}
				elsif ($curr eq "6") { $curr = "7" ;}
				elsif ($curr eq "7") { $curr = "8" ;}
				elsif ($curr eq "8") { $curr = "9" ;}
				elsif ($curr eq "9") { $curr = "9" ;}
				elsif ($curr eq "A") { $curr = "B" ;}
				elsif ($curr eq "B") { $curr = "C" ;}
				elsif ($curr eq "C") { $curr = "C" ;}
				elsif ($curr eq "D") { $curr = "D" ;}
				
			
		} elsif ($m eq "L"){
				if ($curr eq "1") { $curr = "1" ;}
				elsif ($curr eq "2") { $curr = "2" ;}
				elsif ($curr eq "3") { $curr = "2" ;}
				elsif ($curr eq "4") { $curr = "3" ;}
				elsif ($curr eq "5") { $curr = "5" ;}
				elsif ($curr eq "6") { $curr = "5" ;}
				elsif ($curr eq "7") { $curr = "6" ;}
				elsif ($curr eq "8") { $curr = "7" ;}
				elsif ($curr eq "9") { $curr = "8" ;}
				elsif ($curr eq "A") { $curr = "A" ;}
				elsif ($curr eq "B") { $curr = "A" ;}
				elsif ($curr eq "C") { $curr = "B" ;}
				elsif ($curr eq "D") { $curr = "D" ;}
			
		} elsif ($m eq "U"){
				if ($curr eq "1") { $curr = "1" ;}
				elsif ($curr eq "2") { $curr = "2" ;}
				elsif ($curr eq "3") { $curr = "1" ;}
				elsif ($curr eq "4") { $curr = "4" ;}
				elsif ($curr eq "5") { $curr = "5" ;}
				elsif ($curr eq "6") { $curr = "2" ;}
				elsif ($curr eq "7") { $curr = "3" ;}
				elsif ($curr eq "8") { $curr = "4" ;}
				elsif ($curr eq "9") { $curr = "9" ;}
				elsif ($curr eq "A") { $curr = "6" ;}
				elsif ($curr eq "B") { $curr = "7" ;}
				elsif ($curr eq "C") { $curr = "8" ;}
				elsif ($curr eq "D") { $curr = "B" ;}
			
		} elsif ($m eq "D"){
				if ($curr eq "1") { $curr = "3" ;}
				elsif ($curr eq "2") { $curr = "6" ;}
				elsif ($curr eq "3") { $curr = "7" ;}
				elsif ($curr eq "4") { $curr = "8" ;}
				elsif ($curr eq "5") { $curr = "5" ;}
				elsif ($curr eq "6") { $curr = "A" ;}
				elsif ($curr eq "7") { $curr = "B" ;}
				elsif ($curr eq "8") { $curr = "C" ;}
				elsif ($curr eq "9") { $curr = "9" ;}
				elsif ($curr eq "A") { $curr = "A" ;}
				elsif ($curr eq "B") { $curr = "D" ;}
				elsif ($curr eq "C") { $curr = "C" ;}
				elsif ($curr eq "D") { $curr = "D" ;}
			
		}
		#print "$curr \n";
	}
	$code = $code . "$curr"; 
	print "$code \n";

}

print "done. Final code is $code. \n";

